---
title: "DataScienceCapstone"
author: "Nancy"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(readxl)
library(caret)
library(kernlab)
library(dplyr)
library(ggplot2)
library(knitr)
library(manipulate)
library(Hmisc)
library(pastecs)
library(MASS)
library(broom)
library(tidyverse)
library(AppliedPredictiveModeling)
library(maps)
library(shiny)
library(leaflet)
library(leaflet.providers)
library(ggmap)  # For geocoding
library(googleway)
library(scales)
library(rsconnect)
library(gridExtra)
library(plotly)
library(devtools)
library(slidify)

require(stats); require(graphics);require(ggplot2);require(GGally)
install.packages("devtools")
devtools::install_github("ramnathv/slidify",force = TRUE)
devtools::install_github("ramnathv/slidifyLibraries",force = TRUE)


```

```{r echo=FALSE,include=TRUE ,message=FALSE}
# Define the source and destination file paths
destination_file <- "Coursera-SwiftKey.zip"
source_file <- "http://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"

# Check if the file already exists and delete it to ensure fresh download
if (file.exists(destination_file)) {
  file.remove(destination_file)
}

# Execute the download
download.file(source_file, destination_file, mode = "wb")

# Extract the files from the zip file
unzip(destination_file)

# Confirm that the download and extraction were successful
cat("File downloaded and extracted successfully.")

# find out which files where unzipped
unzip(destination_file, list = TRUE )

# inspect the data
list.files("final")
list.files("final/en_US")


```